name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email adress
    required: true
    default: ${{ github.actor }}@localhost
  name: 
    Description: The commiter's name
    required: true
    default: ${{ github.actor }}